'use strict';

// Builds the season calendar (Mon–Fri + Saturday, per week) from the season's
// configured start date, so a new season only needs `season.start` updated in
// season.json rather than a code change. Falls back to LEGACY_SEASON_WEEKS
// below when no start date is configured, which keeps pre-existing seasons
// working unchanged.
function buildSeasonWeeks(season) {
  const start = season && (season.start || season.start_date);
  if (!start || !/^\d{4}-\d{2}-\d{2}$/.test(start)) return LEGACY_SEASON_WEEKS;

  const weekCount = Number(season.weeks) > 0 ? Number(season.weeks) : LEGACY_SEASON_WEEKS.length;
  // Snap back to the Monday of the start date's week so weeks line up Mon–Sat.
  const d = new Date(start + 'T12:00:00Z');
  const dow = d.getUTCDay(); // 0=Sun
  d.setUTCDate(d.getUTCDate() - ((dow + 6) % 7));

  const iso = (dt) => dt.toISOString().slice(0, 10);
  const weeks = [];
  for (let w = 0; w < weekCount; w++) {
    const weekdays = [];
    for (let i = 0; i < 5; i++) {
      const day = new Date(d);
      day.setUTCDate(d.getUTCDate() + (w * 7) + i);
      weekdays.push(iso(day));
    }
    const sat = new Date(d);
    sat.setUTCDate(d.getUTCDate() + (w * 7) + 5);
    weeks.push({ week: w + 1, weekdays, saturday: iso(sat) });
  }
  return weeks;
}

// The original hardcoded spring-2026 calendar, kept as the fallback for any
// season.json that predates `season.start`.
const LEGACY_SEASON_WEEKS = [
  { week: 1, weekdays: ['2026-04-20','2026-04-21','2026-04-22','2026-04-23','2026-04-24'], saturday: '2026-04-25' },
  { week: 2, weekdays: ['2026-04-27','2026-04-28','2026-04-29','2026-04-30','2026-05-01'], saturday: '2026-05-02' },
  { week: 3, weekdays: ['2026-05-04','2026-05-05','2026-05-06','2026-05-07','2026-05-08'], saturday: '2026-05-09' },
  { week: 4, weekdays: ['2026-05-11','2026-05-12','2026-05-13','2026-05-14','2026-05-15'], saturday: '2026-05-16' },
  { week: 5, weekdays: ['2026-05-18','2026-05-19','2026-05-20','2026-05-21','2026-05-22'], saturday: null },   // 5/23 blacked out
  { week: 6, weekdays: ['2026-05-26','2026-05-27','2026-05-28','2026-05-29'],              saturday: '2026-05-30' }, // 5/25 Mon blacked out
  { week: 7, weekdays: ['2026-06-01','2026-06-02','2026-06-03','2026-06-04','2026-06-05'], saturday: '2026-06-06' },
];

// Back-compat alias for callers that don't have a season object to hand.
const SEASON_WEEKS = LEGACY_SEASON_WEEKS;

const DAY_NAMES = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];

function teamName(team) {
  return team.name || team.label || team.team_name || team.full_name || `Team ${team.id}`;
}
// Canonical, order-independent key for a pair of team ids. Sorts as strings
// so it works for both legacy numeric ids and the string ids ('team-<ts>')
// generated by director-created teams — Math.min/max on a non-numeric id
// silently coerces to NaN, which previously collapsed every pair into one
// shared bucket.
// How many games this team wants. Coaches set their own; the division (then
// season) value is the fallback for anyone who hasn't chosen.
function targetFor(team, division, season) {
  const n = Number(team && team.target_games);
  if (Number.isFinite(n) && n > 0) return n;
  return (division && division.target_games) || (season && season.target_games) || 8;
}

function teamPairKey(idA, idB) {
  const [x, y] = [String(idA), String(idB)].sort();
  return `${x}-${y}`;
}
function divName(division) {
  return division.name || division.label || division.id;
}
function dayName(dateStr) {
  const d = new Date(dateStr + 'T12:00:00Z');
  return DAY_NAMES[d.getUTCDay()];
}
function adjacentDate(dateStr, delta) {
  const d = new Date(dateStr + 'T12:00:00Z');
  d.setUTCDate(d.getUTCDate() + delta);
  return d.toISOString().slice(0, 10);
}
function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
function resolveField(team, fields) {
  const fieldId = team.home_field_id;
  const field = fields.find(f => f.id === fieldId);
  if (!field) return null;
  const name = field.sub_field ? `${field.name} – ${field.sub_field}` : field.name;
  return { ...field, name, address: field.address || '', resolved_id: fieldId };
}

// Parses the "lat,lng" string format already used for field coordinates
// (see the Google Maps links in public/app.js). Returns null if missing/malformed.
function parseCoordinates(str) {
  if (!str) return null;
  const parts = str.split(',').map(s => parseFloat(s.trim()));
  if (parts.length !== 2 || !Number.isFinite(parts[0]) || !Number.isFinite(parts[1])) return null;
  return { lat: parts[0], lng: parts[1] };
}

// Haversine distance in miles. Returns null if either point is unavailable.
function distanceMiles(a, b) {
  if (!a || !b) return null;
  const R = 3958.8;
  const dLat = (b.lat - a.lat) * Math.PI / 180;
  const dLng = (b.lng - a.lng) * Math.PI / 180;
  const sinLat = Math.sin(dLat / 2);
  const sinLng = Math.sin(dLng / 2);
  const h = sinLat * sinLat + Math.cos(a.lat * Math.PI / 180) * Math.cos(b.lat * Math.PI / 180) * sinLng * sinLng;
  return R * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

// ── Availability ────────────────────────────────────────────────────────────
//
// Availability is a weekly *pattern* plus per-date *exceptions*. A pattern
// alone ("Tuesdays work") is too blunt across a 10–12 week season — a team can
// be free one Tuesday and not the next — so every lookup resolves against a
// concrete date, checking `dates[YYYY-MM-DD]` first and falling back to the
// pattern, then to fully-available. Anything unset behaves exactly as an
// unconstrained team/field, so partially-filled data keeps working.
//
// Statuses: 'none' | 'host' | 'travel' | 'both'.
//
// Mon–Thu is the coach-configurable grid (per NOTES.md). Friday is schedulable
// but has no UI, so it always resolves to 'both' unless a date exception says
// otherwise.
const WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday'];
const ALL_SCHEDULABLE_WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

// Saturday is three real slots, not time windows. The scheduler places games
// into them based on availability — division/age group no longer dictates the
// time (it used to, via the old saturdayTime()).
const SATURDAY_SLOTS = ['early', 'midday', 'late'];
const SATURDAY_SLOT_TIMES = { early: '10:00', midday: '12:00', late: '14:00' };

// A team is available for a weekday game or it isn't; the exact time is a
// detail the two coaches settle in the change flow, within these bounds.
const WEEKDAY_TIME = '18:30';
const TIME_BOUNDS = { weekday: ['17:00', '19:30'], saturday: ['09:00', '18:00'] };
const TIME_STEP_MINUTES = 30;

function toMinutes(hhmm) {
  const [h, m] = String(hhmm || '').split(':').map(Number);
  return Number.isFinite(h) && Number.isFinite(m) ? h * 60 + m : NaN;
}
// Valid = parseable, inside the day type's window, and on a 30-minute boundary.
function isValidGameTime(hhmm, dayType) {
  const mins = toMinutes(hhmm);
  if (!Number.isFinite(mins)) return false;
  const [lo, hi] = TIME_BOUNDS[dayType === 'saturday' ? 'saturday' : 'weekday'];
  if (mins < toMinutes(lo) || mins > toMinutes(hi)) return false;
  return mins % TIME_STEP_MINUTES === 0;
}
// Every legal kickoff for a day type, for populating pickers.
function allowedTimes(dayType) {
  const [lo, hi] = TIME_BOUNDS[dayType === 'saturday' ? 'saturday' : 'weekday'];
  const out = [];
  for (let m = toMinutes(lo); m <= toMinutes(hi); m += TIME_STEP_MINUTES) {
    out.push(`${String(Math.floor(m / 60)).padStart(2, '0')}:${String(m % 60).padStart(2, '0')}`);
  }
  return out;
}

// Resolves a team's status for one concrete date (+ slot on Saturdays).
// Date exception wins over the weekly pattern, which wins over 'both'.
//
// earliest_date is checked first and unconditionally, before any of that —
// a program that starts up to 3 weeks later than others sets this once
// instead of hand-closing every date in that window. Every scheduling path
// (matchup formation, slot-finding, everything) funnels through this one
// function, so this single check is what makes it fully respected — never
// forced or overridden — everywhere at once.
function resolveTeamAvailability(team, date, dayType, slotKey) {
  if (team?.earliest_date && date < team.earliest_date) return 'none';
  const a = (team && team.availability && typeof team.availability === 'object') ? team.availability : {};
  const ex = a.dates && a.dates[date];
  if (dayType === 'saturday') {
    if (ex && typeof ex === 'object' && ex[slotKey]) return ex[slotKey];
    return (a.saturday && a.saturday[slotKey]) || 'both';
  }
  if (ex && typeof ex === 'object' && ex.status) return ex.status;
  const day = dayName(date);
  const entry = (a.weekday && a.weekday[day]) || {};
  return entry.status || 'both';
}

// Same resolution order for fields, but open/closed rather than four states.
function resolveFieldAvailability(field, date, dayType, slotKey) {
  const a = (field && field.availability && typeof field.availability === 'object') ? field.availability : {};
  const ex = a.dates && a.dates[date];
  if (dayType === 'saturday') {
    if (ex && typeof ex === 'object' && ex[slotKey] !== undefined) return ex[slotKey] !== false;
    return (a.saturday ? a.saturday[slotKey] : true) !== false;
  }
  if (ex !== undefined && ex !== null && typeof ex !== 'object') return ex !== false;
  if (ex && typeof ex === 'object' && ex.status !== undefined) return ex.status !== false;
  const day = dayName(date);
  return (a.weekday ? a.weekday[day] : true) !== false;
}

// A negotiated Saturday time can drift from its slot default (10/12/2), so map
// an arbitrary time back to the closest slot for availability checks.
function nearestSaturdaySlot(time) {
  const mins = toMinutes(time);
  if (!Number.isFinite(mins)) return 'early';
  let best = 'early', bestDelta = Infinity;
  for (const k of SATURDAY_SLOTS) {
    const delta = Math.abs(toMinutes(SATURDAY_SLOT_TIMES[k]) - mins);
    if (delta < bestDelta) { best = k; bestDelta = delta; }
  }
  return best;
}

// True only if a team is host-only on every configurable weekday — the
// pattern-level equivalent of the old blanket `weekday_home_only` flag.
function isWeekdayHostOnly(team) {
  const a = (team && team.availability && typeof team.availability === 'object') ? team.availability : {};
  return WEEKDAYS.every(day => ((a.weekday && a.weekday[day] && a.weekday[day].status) || 'both') === 'host');
}

// ── Slot pool building ────────────────────────────────────────────────────────

function buildAllSlots(globalBlackouts, season) {
  const slots = [];
  for (const wk of buildSeasonWeeks(season)) {
    for (const date of wk.weekdays) {
      if (!globalBlackouts.has(date)) {
        slots.push({ date, week: wk.week, dayType: 'weekday', day: dayName(date), slotKey: null, time: WEEKDAY_TIME });
      }
    }
    if (wk.saturday && !globalBlackouts.has(wk.saturday)) {
      // Three real Saturday slots, so one field can host three games in a day.
      for (const slotKey of SATURDAY_SLOTS) {
        slots.push({ date: wk.saturday, week: wk.week, dayType: 'saturday', day: 'Saturday',
                     slotKey, time: SATURDAY_SLOT_TIMES[slotKey] });
      }
    }
  }
  return slots;
}

// ── Matchup generation ────────────────────────────────────────────────────────
//
// Two-pass round-robin:
//   Pass 1 — non-same-program matchups only (prefer diverse opponents first)
//   Pass 2 — same-program matchups to fill remaining game quota
//
// Within each pass, a fairness check prevents scheduling the Nth game between
// A and B until both have played every other available opponent at least N-1
// times.  This is a soft preference in round-robin order: if a round produces
// no fair games the algorithm keeps cycling until it finds one or gets stuck.
//
// Returns { matchups, shortfall } — shortfall lists any team whose need
// couldn't be fully paired off at all (distinct from a pairing that got
// made but then failed to find a slot, which tryScheduleDivision reports
// separately). Both are real ways a team can come up short, and both need
// to end up visible in the same place — a shortfall here used to just stop
// the loop and vanish with no record, which is exactly the kind of silent
// gap the caller's substitution logic was built to not allow.
// Ted: "not more than 2 times a season... playing a 3rd time means something
// is really wrong" — for a realistic division (6+ teams, his stated norm).
// A flat cap=2 makes the resulting per-team ceiling (maxMeetings*(N-1))
// brutal for a tiny division — 2 teams could never reach more than 2 games
// all season no matter what target_games asks for. Rather than treat that
// as an outlier to special-case after the fact, it's a rule: relax the cap
// as the division gets small enough that 2 meetings genuinely isn't enough
// opponent variety to build a season from. Exported so callers computing a
// team's reachable ceiling (tests, mainly) use this exact rule rather than
// re-deriving a number that could quietly drift from what buildMatchupList
// actually enforces.
function maxMeetingsPerPairFor(teamCount) {
  return teamCount < 4 ? 3 : 2;
}

function buildMatchupList(teams, targetOf, noMatchupRules) {
  if (teams.length < 2) return { matchups: [], shortfall: [] };

  const pairKey = (a, b) => teamPairKey(a.id, b.id);

  const forbidden = new Set();
  for (const rule of (noMatchupRules || [])) {
    for (const a of (rule.team_ids || [])) {
      for (const b of (rule.vs_team_ids || [])) {
        forbidden.add(teamPairKey(a, b));
      }
    }
  }

  const sameProgram = new Set();
  for (let i = 0; i < teams.length; i++) {
    for (let j = i + 1; j < teams.length; j++) {
      if (teams[i].program_id === teams[j].program_id) {
        sameProgram.add(teamPairKey(teams[i].id, teams[j].id));
      }
    }
  }

  // Deficit-driven pairing. Each team has its own target, so this is really a
  // degree-sequence problem: repeatedly pair the two neediest teams that are
  // allowed to meet. A fixed round-robin can't do this — it hands every team
  // one game per round, so a team wanting more than its peers can never
  // outpace them and gets stranded once the others fill up and stop being
  // eligible opponents.
  const need = {};
  const met = {};                       // pairKey -> times already paired
  teams.forEach(t => { need[t.id] = Math.max(0, targetOf(t)); });
  const maxMeetingsPerPair = maxMeetingsPerPairFor(teams.length);

  const matchups = [];
  const maxGames = teams.reduce((s, t) => s + need[t.id], 0);   // safety bound

  while (matchups.length <= maxGames) {
    let best = null, bestScore = null;

    for (let i = 0; i < teams.length; i++) {
      const a = teams[i];
      if (need[a.id] <= 0) continue;
      for (let j = i + 1; j < teams.length; j++) {
        const b = teams[j];
        if (need[b.id] <= 0) continue;
        const key = pairKey(a, b);
        if (forbidden.has(key)) continue;
        // A meeting beyond maxMeetingsPerPair was also the exact trigger for
        // a real home/away-balance bug (the rematch flip only ever flips
        // relative to the *first* meeting, so a 3rd+ meeting could repeat the
        // same side) — capping here removes that scenario at the source
        // rather than trying to make N-way flipping correct. Once two teams
        // have met the limit, they're done with each other for the season;
        // either team's remaining need gets routed to a different opponent
        // instead (the existing substitution loop in scheduleDivision already
        // does exactly this for pairs that turn out unplaceable, so this
        // reuses that same machinery).
        if ((met[key] || 0) >= maxMeetingsPerPair) continue;

        // Lower is better. Spreading opponents matters most (play everyone
        // once before anyone twice), then cross-program over same-program,
        // then serve whoever is furthest from their target.
        // Urgency first: a team whose remaining need is larger than the
        // opponents it has left will starve if opponent-spreading always wins,
        // because the others pair off among themselves and retire. Within
        // equal urgency, still spread opponents and prefer cross-program.
        const urgency = Math.max(need[a.id], need[b.id]);
        const score = [
          -urgency,
          met[key] || 0,
          sameProgram.has(key) ? 1 : 0,
          -Math.min(need[a.id], need[b.id]),
        ];
        if (!bestScore || score.some((v, k) => v !== bestScore[k] && v < bestScore[k]
              && score.slice(0, k).every((x, q) => x === bestScore[q]))) {
          best = [a, b, key]; bestScore = score;
        }
      }
    }

    if (!best) break;                   // nobody left who can legally pair up
    const [a, b, key] = best;
    const cur = met[key] || 0;
    matchups.push({ teamA: a, teamB: b, isSameProgram: sameProgram.has(key),
                    isRematch: cur > 0, round: cur + 1 });
    met[key] = cur + 1;
    need[a.id]--; need[b.id]--;
  }

  const shortfall = teams
    .filter(t => need[t.id] > 0)
    .map(t => ({ team_id: t.id, team_label: teamName(t), missing: need[t.id] }));

  return { matchups, shortfall };
}

// ── Team state tracking ───────────────────────────────────────────────────────

function initTeamState(teams) {
  const state = {};
  teams.forEach(t => {
    state[t.id] = {
      homeCount: 0,
      awayCount: 0,
      gamesPlayed: 0,
      weekdayByWeek: {},
      saturdayByWeek: {},
      weekdayCounts: {},
      opponents: [],
      playedDates: new Set(),
      travelDistance: 0,
    };
  });
  return state;
}

// ── Assignment validity ───────────────────────────────────────────────────────
//
// Enforces each team's recurring weekly availability (status per weekday /
// Saturday block: none/host/travel/both) and the home field's open/closed
// status for that same day or block.
function isValidAssignment(home, away, slot, teamState, fieldUsage, globalBlackouts, fields, season, divisionId, targetOf) {
  const { date, week, dayType } = slot;
  const isSaturday = dayType === 'saturday';
  const homeState = teamState[home.id];
  const awayState = teamState[away.id];

  // Global blackout
  if (globalBlackouts.has(date))
    return { ok: false, reason: `Global blackout on ${date}` };

  // Team blackout dates
  if ((home.blackout_dates || []).includes(date))
    return { ok: false, reason: `${teamName(home)} is blacked out on ${date}` };
  if ((away.blackout_dates || []).includes(date))
    return { ok: false, reason: `${teamName(away)} is blacked out on ${date}` };

  // No two games on the same day
  if (homeState.playedDates.has(date))
    return { ok: false, reason: `${teamName(home)} already has a game on ${date}` };
  if (awayState.playedDates.has(date))
    return { ok: false, reason: `${teamName(away)} already has a game on ${date}` };

  // No consecutive-day games
  const prevDay = adjacentDate(date, -1);
  const nextDay = adjacentDate(date, +1);
  if (homeState.playedDates.has(prevDay) || homeState.playedDates.has(nextDay))
    return { ok: false, reason: `${teamName(home)} would play on consecutive days around ${date}` };
  if (awayState.playedDates.has(prevDay) || awayState.playedDates.has(nextDay))
    return { ok: false, reason: `${teamName(away)} would play on consecutive days around ${date}` };

  // ── Availability enforcement (resolved per concrete date) ────────────────
  const slotKey = slot.slotKey || null;
  const homeStatus = resolveTeamAvailability(home, date, slot.dayType, slotKey);
  const awayStatus = resolveTeamAvailability(away, date, slot.dayType, slotKey);
  const label = isSaturday ? `${slotKey} Saturday (${slot.time}) on ${date}` : `${slot.day} ${date}`;

  if (homeStatus === 'none')
    return { ok: false, reason: `${teamName(home)} is not available for ${label}` };
  if (awayStatus === 'none')
    return { ok: false, reason: `${teamName(away)} is not available for ${label}` };
  if (homeStatus === 'travel')
    return { ok: false, reason: `${teamName(home)} is only available to travel for ${label}, not host` };
  if (awayStatus === 'host')
    return { ok: false, reason: `${teamName(away)} is only available to host for ${label}, not travel` };

  const homeField = resolveField(home, fields || []);
  if (homeField && !resolveFieldAvailability(homeField, date, slot.dayType, slotKey)) {
    return { ok: false, reason: `${homeField.name} is not open to host for ${label}` };
  }

  // ── Hard home/away balance ───────────────────────────────────────────────
  if (targetOf) {
    const homeCap = Math.ceil(targetOf(home) / 2);
    const awayCap = Math.ceil(targetOf(away) / 2);
    if (homeState.homeCount + 1 > homeCap)
      return { ok: false, reason: `${teamName(home)} would exceed its home-game share (${homeCap})` };
    if (awayState.awayCount + 1 > awayCap)
      return { ok: false, reason: `${teamName(away)} would exceed its away-game share (${awayCap})` };
  }
  // The caps alone only guarantee +/-1 for a team that reaches its full target.
  // A team left short by an unplaceable pairing could still drift, so hold the
  // running gap at 1 as well — that keeps the guarantee true of partial
  // schedules too.
  // Allow a temporary drift to 2 while a team still has a game left to correct
  // it with; clamp hard to 1 once this is their last. A strict gap-of-1 at all
  // times forces rigid alternation and costs placeable games for no benefit,
  // since only the FINAL gap is what anyone sees.
  const homeLeftAfter = targetOf ? targetOf(home) - homeState.gamesPlayed - 1 : 99;
  const awayLeftAfter = targetOf ? targetOf(away) - awayState.gamesPlayed - 1 : 99;
  const homeDrift = (homeState.homeCount + 1) - homeState.awayCount;
  const awayDrift = (awayState.awayCount + 1) - awayState.homeCount;
  if (homeDrift > (homeLeftAfter >= 1 ? 2 : 1))
    return { ok: false, reason: `${teamName(home)} would end home-heavy` };
  if (awayDrift > (awayLeftAfter >= 1 ? 2 : 1))
    return { ok: false, reason: `${teamName(away)} would end away-heavy` };

  // ── Week/game-count limits ───────────────────────────────────────────────
  if (!isSaturday) {
    if ((homeState.weekdayByWeek[week] || 0) >= 2)
      return { ok: false, reason: `${teamName(home)} already has 2 weekday games in week ${week}` };
    if ((awayState.weekdayByWeek[week] || 0) >= 2)
      return { ok: false, reason: `${teamName(away)} already has 2 weekday games in week ${week}` };
  }
  if (isSaturday) {
    if ((homeState.saturdayByWeek[week] || 0) >= 1)
      return { ok: false, reason: `${teamName(home)} already has a Saturday game in week ${week}` };
    if ((awayState.saturdayByWeek[week] || 0) >= 1)
      return { ok: false, reason: `${teamName(away)} already has a Saturday game in week ${week}` };
  }

  const homeWeekTotal = (homeState.weekdayByWeek[week] || 0) + (homeState.saturdayByWeek[week] || 0);
  const awayWeekTotal = (awayState.weekdayByWeek[week] || 0) + (awayState.saturdayByWeek[week] || 0);
  if (homeWeekTotal >= 3)
    return { ok: false, reason: `${teamName(home)} already has 3 games in week ${week}` };
  if (awayWeekTotal >= 3)
    return { ok: false, reason: `${teamName(away)} already has 3 games in week ${week}` };

  return { ok: true };
}

// ── Slot finder ───────────────────────────────────────────────────────────────
function findSlot(home, away, slots, teamState, fieldUsage, fields, globalBlackouts, season, divisionId, targetOf) {
  for (const slot of slots) {
    const check = isValidAssignment(home, away, slot, teamState, fieldUsage, globalBlackouts, fields, season, divisionId, targetOf);
    if (!check.ok) continue;

    const field = resolveField(home, fields);
    if (!field) continue;

    // The slot already carries its time (weekday = 18:30, Saturday = its slot
    // time), so time no longer depends on the division. Keying field usage by
    // time rather than date lets one field host all three Saturday slots.
    const time = slot.time;
    const fieldKey = `${field.resolved_id}_${slot.date}_${time}`;
    if (fieldUsage[fieldKey]) continue;

    return {
      game_id: null,
      status: 'scheduled',
      confirmations: { home: false, away: false },
      division_id: divisionId,
      date: slot.date,
      day: slot.day,
      time,
      home_team_id: home.id,
      home_team_name: teamName(home),
      away_team_id: away.id,
      away_team_name: teamName(away),
      field_id: field.resolved_id,
      field_name: field.name,
      field_address: field.address || '',
      week: slot.week,
      is_rematch: false, // set by caller
      _fieldKey: fieldKey,
    };
  }
  return null;
}

function recordGame(game, teamState, fieldUsage) {
  const homeState = teamState[game.home_team_id];
  const awayState = teamState[game.away_team_id];
  const isSaturday = game.day === 'Saturday';

  homeState.homeCount++;
  homeState.gamesPlayed++;
  homeState.opponents.push(game.away_team_id);

  awayState.awayCount++;
  awayState.gamesPlayed++;
  awayState.opponents.push(game.home_team_id);

  if (isSaturday) {
    homeState.saturdayByWeek[game.week] = (homeState.saturdayByWeek[game.week] || 0) + 1;
    awayState.saturdayByWeek[game.week] = (awayState.saturdayByWeek[game.week] || 0) + 1;
  } else {
    homeState.weekdayByWeek[game.week] = (homeState.weekdayByWeek[game.week] || 0) + 1;
    awayState.weekdayByWeek[game.week] = (awayState.weekdayByWeek[game.week] || 0) + 1;
    homeState.weekdayCounts[game.day] = (homeState.weekdayCounts[game.day] || 0) + 1;
    awayState.weekdayCounts[game.day] = (awayState.weekdayCounts[game.day] || 0) + 1;
  }

  homeState.playedDates.add(game.date);
  awayState.playedDates.add(game.date);

  fieldUsage[game._fieldKey] = true;
}

// ── Slot ordering ─────────────────────────────────────────────────────────────
// Hard availability filtering happens in isValidAssignment; this only orders
// the remaining candidate slots (week spread, avoiding a 3rd game in a week,
// day variety).
function buildSlotList(allSlots, teamA, teamB, teamState) {
  const stA = teamState?.[teamA.id];
  const stB = teamState?.[teamB.id];

  const slots = allSlots.map(s => {
    let score = 0;

    // Spread across weeks. Saturday-vs-weekday priority is handled structurally
    // by the two-pass placement, not here — a score term can't express "only if
    // necessary" once week numbers exceed the penalty.
    score += s.week + Math.random() * 0.49;

    // Saturday slot preference: try early -> midday -> late so games cluster at
    // the front of the day, but only as a nudge — availability still decides,
    // which is what replaced the old division/age-group time mapping.
    if (s.dayType === 'saturday' && s.slotKey) {
      score += SATURDAY_SLOTS.indexOf(s.slotKey) * 0.3;
    }

    // 3rd-game-in-week penalty: exhaust all Sat+WD pairs before tripling up
    if (stA && stB) {
      const weekA = (stA.weekdayByWeek[s.week] || 0) + (stA.saturdayByWeek[s.week] || 0);
      const weekB = (stB.weekdayByWeek[s.week] || 0) + (stB.saturdayByWeek[s.week] || 0);
      if (Math.max(weekA, weekB) >= 2) score += 10;
    }

    // Day-variety penalty: discourage repeating the same weekday
    if (s.dayType === 'weekday') {
      const dayA = stA?.weekdayCounts?.[s.day] || 0;
      const dayB = stB?.weekdayCounts?.[s.day] || 0;
      score += (dayA + dayB) * 3;
    }

    return { ...s, _score: score };
  });

  slots.sort((a, b) => a._score - b._score);
  return slots;
}

// ── Division scheduling (one attempt) ────────────────────────────────────────
//
// FIX: Rematch home/away flip — when two teams meet a second time, home and
// away roles are swapped from their first encounter.
//
// Orientation selection accounts for teams that are host-only every weekday
// (isWeekdayHostOnly) when picking who plays home.
//
function tryScheduleDivision(matchups, teams, division, season, fields, globalBlackouts, allSlots, fieldUsage) {
  const teamState = initTeamState(teams);
  const games = [];
  const targetOf = (t) => targetFor(t, division, season);
  const halfOf = (t) => Math.ceil(targetOf(t) / 2);
  const pairKey = (a, b) => teamPairKey(a.id, b.id);

  // Track the MOST RECENT meeting's home/away so a rematch always flips
  // relative to what actually just happened, not to the pair's first-ever
  // meeting. With a flat cap of exactly 2 meetings, "first" and "most
  // recent" are the same thing for a 2nd meeting, so this only mattered once
  // small divisions were allowed a 3rd (maxMeetingsPerPairFor) — a 3rd
  // meeting flipped relative to the 1st was flipping relative to the wrong
  // game, silently repeating the 2nd meeting's side. Ted: home/away must
  // never drift beyond +/-1 — home teams pay for referees, so this isn't
  // negotiable.
  const lastGameOrient = {}; // pairKey → { homeId, awayId } of the most recent meeting
  const unplaced = [];

  // Decide the most travel-consequential pairings first. Orientation is a
  // greedy per-matchup choice, so if the long trips are settled while both
  // teams still have home/away headroom, travel balances far better than if
  // they come up last and the caps have already forced a hand.
  const pairMiles = (m) => {
    const d = distanceMiles(
      parseCoordinates(resolveField(m.teamA, fields)?.coordinates),
      parseCoordinates(resolveField(m.teamB, fields)?.coordinates));
    return d === null ? 0 : d;
  };
  const ordered = [...matchups].sort((a, b) => pairMiles(b) - pairMiles(a));

  for (const matchup of ordered) {
    const { teamA, teamB } = matchup;

    // Detect rematch at runtime so flip works regardless of shuffle order.
    const key = pairKey(teamA, teamB);
    const isActualRematch = !!lastGameOrient[key];

    let orientations;

    if (isActualRematch) {
      // Flip home/away from the most recent meeting between this pair.
      const prev = lastGameOrient[key];
      const prevHome = teams.find(t => t.id === prev.homeId);
      const prevAway = teams.find(t => t.id === prev.awayId);
      if (prevHome && prevAway) {
        orientations = [
          { home: prevAway, away: prevHome }, // flipped (preferred)
          { home: prevHome, away: prevAway }, // repeat (fallback if flip is impossible)
        ];
      }
    }

    if (!orientations) {
      // For weekday-host-only teams, isValidAssignment already enforces home-only on weekdays.
      // Projecting those forced-home weekday games into the effective home count prevents
      // the Saturday orientation from also defaulting to home, which causes imbalance.
      function projectedHomeCount(team) {
        const st = teamState[team.id];
        if (!isWeekdayHostOnly(team)) return st.homeCount;
        const gamesLeft = targetOf(team) - st.gamesPlayed;
        // Conservative: half of remaining games may be weekday (all forced home)
        return st.homeCount + Math.floor(gamesLeft / 2);
      }

      const aAtCap   = projectedHomeCount(teamA) >= halfOf(teamA);
      const bAtCap   = projectedHomeCount(teamB) >= halfOf(teamB);
      const aHomeAdv = teamState[teamA.id].homeCount - teamState[teamA.id].awayCount;
      const bHomeAdv = teamState[teamB.id].homeCount - teamState[teamB.id].awayCount;

      // isWeekdayHostOnly is only a tiebreaker; balance-based signals take priority
      // so Saturday orientation is driven by actual counts, not the hard weekday rule.
      const aWantsHome = isWeekdayHostOnly(teamA);
      const bWantsHome = isWeekdayHostOnly(teamB);

      if (aAtCap && !bAtCap) {
        orientations = [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      } else if (bAtCap && !aAtCap) {
        orientations = [{ home: teamA, away: teamB }, { home: teamB, away: teamA }];
      } else if (aHomeAdv < bHomeAdv) {
        orientations = [{ home: teamA, away: teamB }, { home: teamB, away: teamA }];
      } else if (aHomeAdv > bHomeAdv) {
        orientations = [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      } else if (Math.abs(teamState[teamA.id].travelDistance - teamState[teamB.id].travelDistance) > 0.5) {
        // Travel balance: once home/away counts are level this is the most
        // meaningful remaining signal, so it outranks the weekday-host-only
        // nudge. Whoever has travelled further so far gets to host.
        orientations = teamState[teamA.id].travelDistance > teamState[teamB.id].travelDistance
          ? [{ home: teamA, away: teamB }, { home: teamB, away: teamA }]
          : [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      } else if (aWantsHome && !bWantsHome) {
        orientations = [{ home: teamA, away: teamB }, { home: teamB, away: teamA }];
      } else if (bWantsHome && !aWantsHome) {
        orientations = [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      } else {
        orientations = Math.random() < 0.5
          ? [{ home: teamA, away: teamB }, { home: teamB, away: teamA }]
          : [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      }
    }

    // Ted: home/away must never differ by more than 1 — a hard rule, not a
    // preference. The heuristics above only order which side to *try first*;
    // without this, the fallback orientation could still be used whenever it
    // happened to have an open slot, silently pushing a team's gap to 2+.
    // Actually removing the unbalancing option (rather than just deprioritizing
    // it) means a game that can only be placed by breaking someone's balance
    // goes unplaced instead — reported honestly downstream, same as any other
    // capacity failure, rather than delivered as a schedule that isn't fair.
    const keepsBalance = ({ home, away }) => {
      const h = teamState[home.id], a = teamState[away.id];
      return Math.abs((h.homeCount + 1) - h.awayCount) <= 1
          && Math.abs(a.homeCount - (a.awayCount + 1)) <= 1;
    };
    const safeOrientations = orientations.filter(keepsBalance);
    if (safeOrientations.length > 0) orientations = safeOrientations;
    // If neither orientation keeps both teams balanced, every remaining slot
    // for this matchup would violate someone's +/-1 no matter what — leave
    // the original (unfiltered) list so the search can still place *some*
    // games rather than deadlock the whole division; the outer shuffle+
    // substitution search in scheduleDivision is what actually resolves this
    // by trying a different processing order, not this single matchup.

    let assigned = false;

    const saturdaySlots = allSlots.filter(s => s.dayType === 'saturday');
    const weekdaySlots  = allSlots.filter(s => s.dayType !== 'saturday');

    // Saturdays are the primary vehicle; weekdays only fill what Saturdays
    // genuinely cannot take.
    outer:
    for (const pool of [saturdaySlots, weekdaySlots]) {
    for (const { home, away } of orientations) {
      const slots = buildSlotList(pool, home, away, teamState);
      const game = findSlot(home, away, slots, teamState, fieldUsage, fields, globalBlackouts, season, division.id, targetOf);

      if (game) {
        game.is_rematch = isActualRematch;

        // Always record THIS meeting's orientation — a 3rd+ meeting (small
        // divisions only) needs to flip relative to what just happened, not
        // to the pair's very first encounter.
        lastGameOrient[key] = { homeId: home.id, awayId: away.id };

        recordGame(game, teamState, fieldUsage);

        // Accumulate the away team's travel distance for this game (no-op if either
        // field lacks coordinates), used as an orientation-selection tiebreaker above.
        const dist = distanceMiles(
          parseCoordinates(resolveField(home, fields)?.coordinates),
          parseCoordinates(resolveField(away, fields)?.coordinates)
        );
        if (dist !== null) teamState[away.id].travelDistance += dist;

        games.push(game);
        assigned = true;
        break outer;   // placed — don't fall through to the weekday pool
      }
    }
    }

    if (!assigned) {
      // Record it and carry on. Abandoning the whole division because one
      // pairing won't fit loses every other game that WOULD have worked — at
      // full scale that silently wipes out an entire age group. team_a_id/
      // team_b_id (not just the display names above) let the caller retry
      // with this exact pair excluded, so the two teams get routed to
      // different opponents instead of simply going without.
      unplaced.push({
        division_id: division.id,
        division_name: divName(division),
        blocking_matchup: `${teamName(teamA)} vs ${teamName(teamB)}`,
        team_a_id: teamA.id,
        team_b_id: teamB.id,
        reason: `No valid slot could be found for ${teamName(teamA)} vs ${teamName(teamB)} in ${divName(division)}. ` +
          `Both teams may have conflicting availability, blackouts, full weeks, or field conflicts.`,
      });
    }
  }

  return { success: unplaced.length === 0, games, unplaced, balanceViolations: homeAwayViolations(games, teams) };
}

// Ted: home/away must never differ by more than 1 for any team — "home
// teams pay for refs, so having this be too far out just isn't fair." A
// team with 0 games isn't a violation (nothing to be unfair about yet).
function homeAwayViolations(games, teams) {
  const counts = {};
  teams.forEach(t => { counts[t.id] = { home: 0, away: 0 }; });
  for (const g of games) {
    if (counts[g.home_team_id]) counts[g.home_team_id].home++;
    if (counts[g.away_team_id]) counts[g.away_team_id].away++;
  }
  const violations = [];
  for (const t of teams) {
    const c = counts[t.id];
    if (c && Math.abs(c.home - c.away) > 1) {
      violations.push({ team_id: t.id, team_label: teamName(t), home: c.home, away: c.away });
    }
  }
  return violations;
}

// Schedule one division with multiple shuffle attempts, escalating to
// opponent substitution if a specific pairing proves genuinely impossible.
//
// Every team's target game count matters more than a clean single
// round-robin: if two teams truly can't find a mutually workable slot (zero
// overlapping availability, not just bad luck this attempt), the fix isn't
// to leave both of them a game short — it's to route each of them to a
// different opponent instead, even if that means someone gets a rematch (or,
// worst case, one team's need genuinely can't be fully met because nobody
// left is legally available to it). Confirmed against real fixture data
// before building this: a pairing that fails every one of 100 shuffled
// attempts reliably turns out to have zero compatible day-type in either
// home/away direction — a hard constraint, not contention that a different
// shuffle order would have resolved.
function scheduleDivision(division, teams, season, fields, globalBlackouts, sharedFieldUsage) {
  const targetOf = (t) => targetFor(t, division, season);

  const baseNoMatchupRules = [...(division.no_matchups || [])];
  for (const team of teams) {
    for (const restriction of (team.restrictions || [])) {
      if (restriction.type === 'no_matchup' && restriction.opponent_program_id) {
        const opponentIds = teams
          .filter(t => t.program_id === restriction.opponent_program_id)
          .map(t => t.id);
        if (opponentIds.length) {
          baseNoMatchupRules.push({ team_ids: [team.id], vs_team_ids: opponentIds });
        }
      }
    }
  }

  const allSlots = buildAllSlots(globalBlackouts, season);
  const fieldUsageSnapshot = { ...sharedFieldUsage };
  const MAX_ATTEMPTS = 100;
  const MAX_SUBSTITUTION_ROUNDS = 12;

  // Keyed by teamPairKey (order-independent, dedupes naturally) but stores
  // the actual id pair as the value — team ids can themselves contain
  // dashes (e.g. "team-12"), so the dash-joined key isn't safe to split
  // back apart.
  const forbiddenPairs = new Map();
  let lastBest = null, lastBestUsage = null, lastShortfall = [];

  // A team whose need never got fully paired off (distinct from a pairing
  // that was made but then failed to schedule) into the same shape as a
  // scheduling failure, so both end up visible through the same reporting
  // path instead of one type silently having no record at all.
  const shortfallToFailures = (shortfall) => shortfall.map(s => ({
    division_id: division.id,
    division_name: divName(division),
    blocking_matchup: `${s.team_label} — not enough eligible opponents left`,
    team_a_id: s.team_id, team_b_id: null,
    reason: `${s.team_label} is ${s.missing} game(s) short of its target with no legal opponent ` +
      `remaining to pair against — likely the ${maxMeetingsPerPairFor(teams.length)}-meetings-per-opponent cap ` +
      `combined with a small division, or every remaining opponent already forbidden/unavailable.`,
  }));

  // Ted: home/away must never differ by more than 1 — "home teams pay for
  // refs, so having this be too far out just isn't fair." Reported the same
  // way as any other failure if the search genuinely can't avoid it, rather
  // than silently handing back an unfair schedule.
  const balanceToFailures = (violations) => violations.map(v => ({
    division_id: division.id,
    division_name: divName(division),
    blocking_matchup: `${v.team_label} — home/away imbalance`,
    team_a_id: v.team_id, team_b_id: null,
    reason: `${v.team_label} ended up ${v.home} home / ${v.away} away, a ${Math.abs(v.home - v.away)}-game gap. ` +
      `Home/away must stay within 1 of each other — home teams cover referee costs.`,
  }));

  // Priority for picking the best of several shuffle attempts: fewest
  // unplaced games first (a missing game is worse than an unfair one), then
  // fewest balance violations, then most games actually placed.
  const attemptScore = (r) => [r.unplaced.length, r.balanceViolations.length, -r.games.length];
  const isBetterAttempt = (candidate, current) => {
    const a = attemptScore(candidate), b = attemptScore(current);
    for (let i = 0; i < a.length; i++) { if (a[i] !== b[i]) return a[i] < b[i]; }
    return false;
  };

  for (let round = 0; round < MAX_SUBSTITUTION_ROUNDS; round++) {
    const extraRules = [...forbiddenPairs.values()].map(([a, b]) => ({ team_ids: [a], vs_team_ids: [b] }));
    const { matchups: matchupList, shortfall } = buildMatchupList(teams, targetOf, [...baseNoMatchupRules, ...extraRules]);
    lastShortfall = shortfall;

    if (matchupList.length === 0) {
      if (round > 0 && lastBest) break; // substitution has nothing left to try — fall through to the best attempt so far
      return {
        success: false,
        failure: {
          division_id: division.id,
          division_name: divName(division),
          reason: 'No valid matchups could be generated (check no_matchup rules and team count)',
        },
      };
    }

    // Forbidding a pairing can, in rare cases, leave a team with no legal
    // opponent left at all — buildMatchupList just quietly excludes it, with
    // no failure to react to, since it never got as far as trying to
    // schedule anything. That's a worse outcome than what this was meant to
    // fix (a team with zero games instead of one short), so back off to the
    // previous round rather than accept it.
    if (round > 0) {
      const involved = new Set();
      for (const m of matchupList) { involved.add(m.teamA.id); involved.add(m.teamB.id); }
      const stranded = teams.some(t => targetOf(t) > 0 && !involved.has(t.id));
      if (stranded) break;
    }

    let best = null, bestUsage = null;
    for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
      Object.keys(sharedFieldUsage).forEach(k => delete sharedFieldUsage[k]);
      Object.assign(sharedFieldUsage, fieldUsageSnapshot);

      const shuffled = shuffle([...matchupList]);
      const result = tryScheduleDivision(
        shuffled, teams, division, season, fields, globalBlackouts, allSlots, sharedFieldUsage
      );

      if (result.success && result.balanceViolations.length === 0) {
        best = result; bestUsage = { ...sharedFieldUsage }; break;
      }
      if (!best || isBetterAttempt(result, best)) {
        best = result;
        bestUsage = { ...sharedFieldUsage };
      }
    }

    lastBest = best;
    lastBestUsage = bestUsage;

    if (best.success && best.balanceViolations.length === 0) {
      Object.keys(sharedFieldUsage).forEach(k => delete sharedFieldUsage[k]);
      Object.assign(sharedFieldUsage, bestUsage);
      const shortfallFailures = shortfallToFailures(shortfall);
      return { success: shortfallFailures.length === 0, games: best.games, division_id: division.id,
               unplaced: shortfallFailures };
    }

    // Only escalate on pairings we haven't already forbidden — if every
    // failure this round is already known, a fresh matchup list won't
    // discover anything new, so stop rather than loop pointlessly.
    const newPairs = best.unplaced
      .filter(u => u.team_a_id != null && u.team_b_id != null)
      .filter(u => !forbiddenPairs.has(teamPairKey(u.team_a_id, u.team_b_id)));
    if (newPairs.length === 0) break;
    for (const u of newPairs) forbiddenPairs.set(teamPairKey(u.team_a_id, u.team_b_id), [u.team_a_id, u.team_b_id]);
  }

  Object.keys(sharedFieldUsage).forEach(k => delete sharedFieldUsage[k]);
  Object.assign(sharedFieldUsage, lastBestUsage || fieldUsageSnapshot);

  return { success: false, games: (lastBest && lastBest.games) || [], division_id: division.id,
           unplaced: [
             ...((lastBest && lastBest.unplaced) || []),
             ...shortfallToFailures(lastShortfall),
             ...balanceToFailures((lastBest && lastBest.balanceViolations) || []),
           ] };
}

// ── Top-level ─────────────────────────────────────────────────────────────────
//
// Pre-run validation flags confirmed teams/fields that haven't configured
// availability yet (they default to fully open, so this is informational,
// not blocking) — surfaced in the result as `warnings` for the UI.
//
function scheduleAll(seasonData) {
  const season = seasonData.season;
  const fields = seasonData.fields || [];
  const globalBlackouts = new Set(season.blackout_dates || []);
  for (const weekend of (season.blackout_weekends || [])) {
    if (Array.isArray(weekend.dates)) weekend.dates.forEach(d => globalBlackouts.add(d));
    if (weekend.saturday) globalBlackouts.add(weekend.saturday);
    if (weekend.sunday)   globalBlackouts.add(weekend.sunday);
  }

  const warnings = [];
  for (const team of (seasonData.teams || [])) {
    if (team.confirmed === false) continue;
    if (!team.availability) {
      warnings.push({
        type: 'availability_warning',
        team_id: team.id,
        team_name: teamName(team),
        message: `${teamName(team)} has not set availability — defaulting to fully available`,
      });
    }
  }
  for (const field of fields) {
    if (!field.availability) {
      warnings.push({
        type: 'availability_warning',
        field_id: field.id,
        message: `${field.name} has not set availability — defaulting to fully open`,
      });
    }
  }

  const allGames = [];
  const failures = [];
  let gameIdCounter = 1;

  const startYear = (season.start || season.start_date || '').slice(2, 4)
    || String(new Date().getFullYear()).slice(2);
  const seasonName = (season.name || '').toLowerCase();
  const seasonNum = seasonName.includes('fall') ? '2' : '1';
  const gameIdPrefix = startYear + seasonNum;

  const sharedFieldUsage = {};

  for (const division of seasonData.divisions) {
    const divTeams = (seasonData.teams || []).filter(t =>
      t.division_id === division.id && t.confirmed !== false
    );

    if (divTeams.length < 2) {
      failures.push({
        division_id: division.id,
        division_name: divName(division),
        reason: `Only ${divTeams.length} confirmed team(s) — need at least 2`,
      });
      continue;
    }

    const result = scheduleDivision(division, divTeams, season, fields, globalBlackouts, sharedFieldUsage);

    // Keep whatever was placed, even on a partial result — a division with
    // 23 of 24 games plus a clear warning beats an empty division.
    for (const game of (result.games || [])) {
      game.game_id = parseInt(gameIdPrefix + String(gameIdCounter++).padStart(3, '0'), 10);
    }
    allGames.push(...(result.games || []));

    for (const u of (result.unplaced || [])) failures.push(u);
  }

  return {
    success: failures.length === 0,
    games: allGames,
    failures,
    warnings,  // NEW: soft warnings surfaced to the UI
    generated_at: new Date().toISOString(),
    total_games: allGames.length,
  };
}

// ── Game edit validation ──────────────────────────────────────────────────────

function validateGameEdit(editedGame, allGames, season) {
  const violations = [];
  const { id, date, time, field_id, home_team_id, away_team_id } = editedGame;

  if (home_team_id === away_team_id) {
    violations.push('Home team and away team cannot be the same.');
  }

  const globalBlackouts = new Set(season.blackout_dates || []);
  if (season.blackout_weekends) {
    for (const weekend of season.blackout_weekends) {
      if (weekend.saturday) globalBlackouts.add(weekend.saturday);
      if (weekend.sunday)   globalBlackouts.add(weekend.sunday);
      if (weekend.dates)    for (const d of weekend.dates) globalBlackouts.add(d);
    }
  }

  let weekEntry = null;
  let dateType = null;
  for (const wk of buildSeasonWeeks(season)) {
    if (wk.weekdays.includes(date)) { weekEntry = wk; dateType = 'weekday'; break; }
    if (wk.saturday === date)        { weekEntry = wk; dateType = 'saturday'; break; }
  }

  if (!weekEntry) {
    violations.push(`${date} is not a valid season date.`);
    return violations;
  }

  if (globalBlackouts.has(date)) {
    violations.push(`${date} is a global blackout date.`);
  }

  const teams = season._teams || [];
  const homeTeam = teams.find(t => t.id === home_team_id);
  const awayTeam = teams.find(t => t.id === away_team_id);

  if (homeTeam && (homeTeam.blackout_dates || []).includes(date))
    violations.push(`Home team (${teamName(homeTeam)}) is blacked out on ${date}.`);
  if (awayTeam && (awayTeam.blackout_dates || []).includes(date))
    violations.push(`Away team (${teamName(awayTeam)}) is blacked out on ${date}.`);

  // Cancelled (rained-out) games no longer occupy their old slot — otherwise
  // a rainout's own former date/field would permanently block itself (and
  // everyone else) from ever reusing that slot for a makeup.
  const others = allGames.filter(g => g.game_id !== id && g.id !== id && g.status !== 'cancelled');

  const fieldConflict = others.find(g => g.field_id === field_id && g.date === date && g.time === time);
  if (fieldConflict)
    violations.push(`Field is already booked at ${date} ${time} (game #${fieldConflict.game_id || fieldConflict.id}).`);

  const homeConflict = others.find(g =>
    (g.home_team_id === home_team_id || g.away_team_id === home_team_id) && g.date === date && g.time === time
  );
  if (homeConflict)
    violations.push(`Home team already has a game at ${date} ${time}.`);

  const awayConflict = others.find(g =>
    (g.home_team_id === away_team_id || g.away_team_id === away_team_id) && g.date === date && g.time === time
  );
  if (awayConflict)
    violations.push(`Away team already has a game at ${date} ${time}.`);

  const week = weekEntry.week;
  const isSaturday = dateType === 'saturday';
  const day = dayName(date);

  // ── Consecutive-day check ──────────────────────────────────────────────────
  const prevDay = adjacentDate(date, -1);
  const nextDay = adjacentDate(date, +1);
  const homeConsec = others.find(g =>
    (g.home_team_id === home_team_id || g.away_team_id === home_team_id) &&
    (g.date === prevDay || g.date === nextDay)
  );
  if (homeConsec)
    violations.push(`Home team would play on consecutive days (existing game on ${homeConsec.date}).`);
  const awayConsec = others.find(g =>
    (g.home_team_id === away_team_id || g.away_team_id === away_team_id) &&
    (g.date === prevDay || g.date === nextDay)
  );
  if (awayConsec)
    violations.push(`Away team would play on consecutive days (existing game on ${awayConsec.date}).`);

  // ── Team availability checks (soft — informational, "Save Anyway" overrides) ──
  const dayType = isSaturday ? 'saturday' : 'weekday';
  const slotKey = isSaturday ? nearestSaturdaySlot(time) : null;
  const availLabel = isSaturday ? `${slotKey} Saturday (${time}) on ${date}` : `${day} ${date}`;
  if (homeTeam) {
    const homeStatus = resolveTeamAvailability(homeTeam, date, dayType, slotKey);
    if (homeStatus === 'none')
      violations.push(`Home team (${teamName(homeTeam)}) is not available for ${availLabel}.`);
    else if (homeStatus === 'travel')
      violations.push(`Home team (${teamName(homeTeam)}) is only available to travel for ${availLabel}, not host.`);
  }
  if (awayTeam) {
    const awayStatus = resolveTeamAvailability(awayTeam, date, dayType, slotKey);
    if (awayStatus === 'none')
      violations.push(`Away team (${teamName(awayTeam)}) is not available for ${availLabel}.`);
    else if (awayStatus === 'host')
      violations.push(`Away team (${teamName(awayTeam)}) is only available to host for ${availLabel}, not travel.`);
  }
  if (!isValidGameTime(time, dayType)) {
    const [lo, hi] = TIME_BOUNDS[dayType];
    violations.push(`${time} is outside the allowed window (${lo}–${hi}, on the half hour).`);
  }

  if (isSaturday) {
    const homeSat = others.filter(g =>
      (g.home_team_id === home_team_id || g.away_team_id === home_team_id) &&
      g.week === week && g.day === 'Saturday'
    ).length;
    if (homeSat >= 1) violations.push(`Home team already has a Saturday game in week ${week}.`);

    const awaySat = others.filter(g =>
      (g.home_team_id === away_team_id || g.away_team_id === away_team_id) &&
      g.week === week && g.day === 'Saturday'
    ).length;
    if (awaySat >= 1) violations.push(`Away team already has a Saturday game in week ${week}.`);
  } else {
    const homeWd = others.filter(g =>
      (g.home_team_id === home_team_id || g.away_team_id === home_team_id) &&
      g.week === week && g.day !== 'Saturday'
    ).length;
    if (homeWd >= 2) violations.push(`Home team already has 2 weekday games in week ${week}.`);

    const awayWd = others.filter(g =>
      (g.home_team_id === away_team_id || g.away_team_id === away_team_id) &&
      g.week === week && g.day !== 'Saturday'
    ).length;
    if (awayWd >= 2) violations.push(`Away team already has 2 weekday games in week ${week}.`);

    const homeTot = others.filter(g =>
      (g.home_team_id === home_team_id || g.away_team_id === home_team_id) && g.week === week
    ).length;
    if (homeTot >= 3) violations.push(`Home team already has 3 games in week ${week}.`);

    const awayTot = others.filter(g =>
      (g.home_team_id === away_team_id || g.away_team_id === away_team_id) && g.week === week
    ).length;
    if (awayTot >= 3) violations.push(`Away team already has 3 games in week ${week}.`);
  }

  return violations;
}

module.exports = {
  scheduleAll, validateGameEdit, SEASON_WEEKS, dayName, teamName,
  // Exported so server-side tools (e.g. the admin's date-suggestion endpoint)
  // apply the same availability rules as the scheduler itself.
  resolveTeamAvailability, resolveFieldAvailability, nearestSaturdaySlot, buildSeasonWeeks,
  SATURDAY_SLOTS, SATURDAY_SLOT_TIMES, WEEKDAY_TIME, TIME_BOUNDS, isValidGameTime, allowedTimes,
  maxMeetingsPerPairFor,
};
