'use strict';

// Season week definitions per spec calendar
const SEASON_WEEKS = [
  { week: 1, weekdays: ['2026-04-20','2026-04-21','2026-04-22','2026-04-23','2026-04-24'], saturday: '2026-04-25' },
  { week: 2, weekdays: ['2026-04-27','2026-04-28','2026-04-29','2026-04-30','2026-05-01'], saturday: '2026-05-02' },
  { week: 3, weekdays: ['2026-05-04','2026-05-05','2026-05-06','2026-05-07','2026-05-08'], saturday: '2026-05-09' },
  { week: 4, weekdays: ['2026-05-11','2026-05-12','2026-05-13','2026-05-14','2026-05-15'], saturday: '2026-05-16' },
  { week: 5, weekdays: ['2026-05-18','2026-05-19','2026-05-20','2026-05-21','2026-05-22'], saturday: null },   // 5/23 blacked out
  { week: 6, weekdays: ['2026-05-26','2026-05-27','2026-05-28','2026-05-29'],              saturday: '2026-05-30' }, // 5/25 Mon blacked out
  { week: 7, weekdays: ['2026-06-01','2026-06-02','2026-06-03','2026-06-04','2026-06-05'], saturday: '2026-06-06' },
];

const DAY_NAMES = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];

function teamName(team) {
  return team.name || team.label || team.team_name || team.full_name || `Team ${team.id}`;
}
// Canonical, order-independent key for a pair of team ids. Sorts as strings
// so it works for both legacy numeric ids and the string ids ('team-<ts>')
// generated by director-created teams — Math.min/max on a non-numeric id
// silently coerces to NaN, which previously collapsed every pair into one
// shared bucket.
function teamPairKey(idA, idB) {
  const [x, y] = [String(idA), String(idB)].sort();
  return `${x}-${y}`;
}
function divName(division) {
  return division.name || division.label || division.id;
}
function dayName(dateStr) {
  const d = new Date(dateStr + 'T12:00:00Z');
  return DAY_NAMES[d.getUTCDay()];
}
function adjacentDate(dateStr, delta) {
  const d = new Date(dateStr + 'T12:00:00Z');
  d.setUTCDate(d.getUTCDate() + delta);
  return d.toISOString().slice(0, 10);
}
function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
function saturdayTime(divisionId, season) {
  const ageGroup = divisionId.split('-')[0];
  const times = season.saturday_times || season.weekend_times;
  return (times && times[ageGroup]) || '10:00';
}
function resolveField(team, fields) {
  const fieldId = team.home_field_id;
  const field = fields.find(f => f.id === fieldId);
  if (!field) return null;
  const name = field.sub_field ? `${field.name} – ${field.sub_field}` : field.name;
  return { ...field, name, address: field.address || '', resolved_id: fieldId };
}

// Parses the "lat,lng" string format already used for field coordinates
// (see the Google Maps links in public/app.js). Returns null if missing/malformed.
function parseCoordinates(str) {
  if (!str) return null;
  const parts = str.split(',').map(s => parseFloat(s.trim()));
  if (parts.length !== 2 || !Number.isFinite(parts[0]) || !Number.isFinite(parts[1])) return null;
  return { lat: parts[0], lng: parts[1] };
}

// Haversine distance in miles. Returns null if either point is unavailable.
function distanceMiles(a, b) {
  if (!a || !b) return null;
  const R = 3958.8;
  const dLat = (b.lat - a.lat) * Math.PI / 180;
  const dLng = (b.lng - a.lng) * Math.PI / 180;
  const sinLat = Math.sin(dLat / 2);
  const sinLng = Math.sin(dLng / 2);
  const h = sinLat * sinLat + Math.cos(a.lat * Math.PI / 180) * Math.cos(b.lat * Math.PI / 180) * sinLng * sinLng;
  return R * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

// ── Availability parsing ────────────────────────────────────────────────────────
//
// Structured recurring-weekly availability, replacing the old string-code
// `team.preferences` system. Each weekday has a status ('none'/'host'/'travel'/
// 'both') plus an optional start-time override; Saturday is split into three
// blocks (before11/mid/after2) with the same status vocabulary. Anything
// unset defaults to 'both' (unconstrained) so teams/fields that haven't
// filled out the new form keep scheduling exactly as an unconstrained
// team/field would.
//
// Mon–Thu is the coach/director-configurable grid (per NOTES.md). Friday is a
// schedulable weekday too (see SEASON_WEEKS) but has no UI — it always
// defaults to 'both' below, same as any other unconfigured day.
const WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday'];
const ALL_SCHEDULABLE_WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
const SATURDAY_BLOCKS = ['before11', 'mid', 'after2'];

function parseAvailability(team) {
  const a = (team.availability && typeof team.availability === 'object') ? team.availability : {};
  const weekday = {};
  for (const day of ALL_SCHEDULABLE_WEEKDAYS) {
    const entry = (a.weekday && a.weekday[day]) || {};
    weekday[day] = { status: entry.status || 'both', time: entry.time || null };
  }
  const saturday = {};
  for (const block of SATURDAY_BLOCKS) {
    saturday[block] = (a.saturday && a.saturday[block]) || 'both';
  }
  return { weekday, saturday };
}

function parseFieldAvailability(field) {
  const a = (field && field.availability && typeof field.availability === 'object') ? field.availability : {};
  const weekday = {};
  for (const day of ALL_SCHEDULABLE_WEEKDAYS) weekday[day] = (a.weekday ? a.weekday[day] : true) !== false;
  const saturday = {};
  for (const block of SATURDAY_BLOCKS) saturday[block] = (a.saturday ? a.saturday[block] : true) !== false;
  return { weekday, saturday };
}

// Maps a Saturday game's 'HH:MM' time to which of the three availability blocks it falls in.
function saturdayBlock(time) {
  if (time < '11:00') return 'before11';
  if (time < '14:00') return 'mid';
  return 'after2';
}

// True only if a team is host-only on every UI-configurable weekday (Mon–Thu)
// — the recurring-pattern equivalent of the old blanket `weekday_home_only`
// flag. Deliberately excludes Friday, which has no UI and always defaults to
// 'both', so it can never itself trigger this.
function isWeekdayHostOnly(availability) {
  return WEEKDAYS.every(day => availability.weekday[day].status === 'host');
}

// ── Slot pool building ────────────────────────────────────────────────────────

function buildAllSlots(globalBlackouts) {
  const slots = [];
  for (const wk of SEASON_WEEKS) {
    for (const date of wk.weekdays) {
      if (!globalBlackouts.has(date)) {
        slots.push({ date, week: wk.week, dayType: 'weekday', day: dayName(date) });
      }
    }
    if (wk.saturday && !globalBlackouts.has(wk.saturday)) {
      slots.push({ date: wk.saturday, week: wk.week, dayType: 'saturday', day: 'Saturday' });
    }
  }
  return slots;
}

// ── Matchup generation ────────────────────────────────────────────────────────
//
// Two-pass round-robin:
//   Pass 1 — non-same-program matchups only (prefer diverse opponents first)
//   Pass 2 — same-program matchups to fill remaining game quota
//
// Within each pass, a fairness check prevents scheduling the Nth game between
// A and B until both have played every other available opponent at least N-1
// times.  This is a soft preference in round-robin order: if a round produces
// no fair games the algorithm keeps cycling until it finds one or gets stuck.
//
function buildMatchupList(teams, targetGames, noMatchupRules) {
  if (teams.length < 2) return [];

  const pairKey = (a, b) => teamPairKey(a.id, b.id);

  const forbidden = new Set();
  for (const rule of (noMatchupRules || [])) {
    for (const a of (rule.team_ids || [])) {
      for (const b of (rule.vs_team_ids || [])) {
        forbidden.add(teamPairKey(a, b));
      }
    }
  }

  const sameProgram = new Set();
  for (let i = 0; i < teams.length; i++) {
    for (let j = i + 1; j < teams.length; j++) {
      if (teams[i].program_id === teams[j].program_id) {
        sameProgram.add(teamPairKey(teams[i].id, teams[j].id));
      }
    }
  }

  function generateRRRounds(teamList) {
    const list = teamList.length % 2 === 0 ? [...teamList] : [...teamList, null];
    const n = list.length;
    const fixed = list[n - 1];
    const rotating = [...list.slice(0, n - 1)];
    const rounds = [];
    for (let r = 0; r < n - 1; r++) {
      const round = [];
      if (fixed && rotating[0]) round.push([fixed, rotating[0]]);
      for (let i = 1; i < n / 2; i++) {
        const a = rotating[i];
        const b = rotating[(n - 1) - i];
        if (a && b) round.push([a, b]);
      }
      rotating.unshift(rotating.pop());
      rounds.push(round);
    }
    return rounds;
  }

  // Check whether adding the (currentCount+1)th game between side and other
  // would violate the spread-≤1 fairness rule.  Returns true if the game
  // should be skipped (unfair), false if it may proceed.
  // Only opponents valid in the current pass (same filterSameProgram) are considered,
  // so same-program teams don't block cross-program rematches in pass 1 (and vice versa).
  function isFairnessViolation(side, other, currentCount, filterSameProgram) {
    if (currentCount === 0) return false;
    for (const opp of teams) {
      if (opp.id === side.id || opp.id === other.id) continue;
      if (gameCounts[opp.id] >= targetGames) continue;
      const oppKey = pairKey(side, opp);
      if (forbidden.has(oppKey)) continue;
      if (sameProgram.has(oppKey) !== filterSameProgram) continue;
      if ((matchupCounts[oppKey] || 0) < currentCount) return true;
    }
    return false;
  }

  const rrRounds = generateRRRounds(teams);
  const gameCounts = {};
  const crossProgramGames = {};
  const matchupCounts = {};
  teams.forEach(t => { gameCounts[t.id] = 0; crossProgramGames[t.id] = 0; });

  const matchups = [];

  for (const filterSameProgram of [false, true]) {
    let roundIdx = 0;
    const MAX_ROUNDS = rrRounds.length * (targetGames * 6 + 10);

    const isDone = (t) => gameCounts[t.id] >= targetGames;

    while (roundIdx < MAX_ROUNDS) {
      if (teams.every(t => gameCounts[t.id] >= targetGames)) break;

      const round = rrRounds[roundIdx % rrRounds.length];
      roundIdx++;

      // Prioritize pairs where teams have fewest games (same-program members catch up together).
      const sortedRound = [...round].sort((pA, pB) => {
        const minA = Math.min(gameCounts[pA[0].id], gameCounts[pA[1].id]);
        const minB = Math.min(gameCounts[pB[0].id], gameCounts[pB[1].id]);
        return minA - minB;
      });

      // Collect fair and unfair games separately for this round;
      // add fair ones immediately, defer unfair ones until round is done.
      const deferred = [];

      for (const [teamA, teamB] of sortedRound) {
        const key = pairKey(teamA, teamB);
        if (forbidden.has(key)) continue;
        if (isDone(teamA)) continue;
        if (isDone(teamB)) continue;
        if (sameProgram.has(key) !== filterSameProgram) continue;

        const currentCount = matchupCounts[key] || 0;
        const unfairA = isFairnessViolation(teamA, teamB, currentCount, filterSameProgram);
        const unfairB = isFairnessViolation(teamB, teamA, currentCount, filterSameProgram);

        if (unfairA || unfairB) {
          deferred.push({ teamA, teamB, key, currentCount });
        } else {
          matchups.push({ teamA, teamB, isSameProgram: filterSameProgram, isRematch: currentCount > 0, round: currentCount + 1 });
          gameCounts[teamA.id]++;
          gameCounts[teamB.id]++;
          if (!filterSameProgram) { crossProgramGames[teamA.id]++; crossProgramGames[teamB.id]++; }
          matchupCounts[key] = currentCount + 1;
        }
      }

      // Add deferred (unfair) games only if neither team has a fair alternative
      // available in this pass.  This prevents a same-program pair from being
      // scheduled repeatedly while a fairer pairing still exists.
      for (const { teamA, teamB, key, currentCount } of deferred) {
        if (isDone(teamA)) continue;
        if (isDone(teamB)) continue;

        const hasFairAlt = (side) => teams.some(opp => {
          if (opp.id === side.id || opp.id === teamA.id || opp.id === teamB.id) return false;
          if (isDone(opp)) return false;
          const k = pairKey(side, opp);
          if (forbidden.has(k)) return false;
          if (sameProgram.has(k) !== filterSameProgram) return false;
          return !isFairnessViolation(side, opp, matchupCounts[k] || 0, filterSameProgram);
        });

        if (hasFairAlt(teamA) || hasFairAlt(teamB)) continue;

        matchups.push({ teamA, teamB, isSameProgram: filterSameProgram, isRematch: currentCount > 0, round: currentCount + 1 });
        gameCounts[teamA.id]++;
        gameCounts[teamB.id]++;
        if (!filterSameProgram) { crossProgramGames[teamA.id]++; crossProgramGames[teamB.id]++; }
        matchupCounts[key] = currentCount + 1;
      }

      const stuck = teams.every(t => {
        if (isDone(t)) return true;
        return teams.every(other => {
          if (other.id === t.id) return true;
          const key = pairKey(t, other);
          if (forbidden.has(key)) return true;
          if (isDone(other)) return true;
          return sameProgram.has(key) !== filterSameProgram;
        });
      });
      if (stuck) break;
    }
  }

  return matchups;
}

// ── Team state tracking ───────────────────────────────────────────────────────

function initTeamState(teams) {
  const state = {};
  teams.forEach(t => {
    state[t.id] = {
      homeCount: 0,
      awayCount: 0,
      gamesPlayed: 0,
      weekdayByWeek: {},
      saturdayByWeek: {},
      weekdayCounts: {},
      opponents: [],
      playedDates: new Set(),
      travelDistance: 0,
    };
  });
  return state;
}

// ── Assignment validity ───────────────────────────────────────────────────────
//
// Enforces each team's recurring weekly availability (status per weekday /
// Saturday block: none/host/travel/both) and the home field's open/closed
// status for that same day or block.
function isValidAssignment(home, away, slot, teamState, fieldUsage, globalBlackouts, fields, season, divisionId) {
  const { date, week, dayType } = slot;
  const isSaturday = dayType === 'saturday';
  const homeState = teamState[home.id];
  const awayState = teamState[away.id];

  // Global blackout
  if (globalBlackouts.has(date))
    return { ok: false, reason: `Global blackout on ${date}` };

  // Team blackout dates
  if ((home.blackout_dates || []).includes(date))
    return { ok: false, reason: `${teamName(home)} is blacked out on ${date}` };
  if ((away.blackout_dates || []).includes(date))
    return { ok: false, reason: `${teamName(away)} is blacked out on ${date}` };

  // No two games on the same day
  if (homeState.playedDates.has(date))
    return { ok: false, reason: `${teamName(home)} already has a game on ${date}` };
  if (awayState.playedDates.has(date))
    return { ok: false, reason: `${teamName(away)} already has a game on ${date}` };

  // No consecutive-day games
  const prevDay = adjacentDate(date, -1);
  const nextDay = adjacentDate(date, +1);
  if (homeState.playedDates.has(prevDay) || homeState.playedDates.has(nextDay))
    return { ok: false, reason: `${teamName(home)} would play on consecutive days around ${date}` };
  if (awayState.playedDates.has(prevDay) || awayState.playedDates.has(nextDay))
    return { ok: false, reason: `${teamName(away)} would play on consecutive days around ${date}` };

  // ── Availability enforcement ─────────────────────────────────────────────
  const homeAvail = parseAvailability(home);
  const awayAvail = parseAvailability(away);
  const key = isSaturday ? saturdayBlock(saturdayTime(divisionId, season)) : slot.day;
  const homeStatus = isSaturday ? homeAvail.saturday[key] : homeAvail.weekday[key].status;
  const awayStatus = isSaturday ? awayAvail.saturday[key] : awayAvail.weekday[key].status;
  const label = isSaturday ? `the ${key} Saturday block` : key;

  if (homeStatus === 'none')
    return { ok: false, reason: `${teamName(home)} is not available for ${label}` };
  if (awayStatus === 'none')
    return { ok: false, reason: `${teamName(away)} is not available for ${label}` };
  if (homeStatus === 'travel')
    return { ok: false, reason: `${teamName(home)} is only available to travel for ${label}, not host` };
  if (awayStatus === 'host')
    return { ok: false, reason: `${teamName(away)} is only available to host for ${label}, not travel` };

  const homeField = resolveField(home, fields || []);
  if (homeField) {
    const fieldAvail = parseFieldAvailability(homeField);
    const fieldOpen = isSaturday ? fieldAvail.saturday[key] : fieldAvail.weekday[key];
    if (!fieldOpen)
      return { ok: false, reason: `${homeField.name} is not open to host for ${label}` };
  }

  // ── Week/game-count limits ───────────────────────────────────────────────
  if (!isSaturday) {
    if ((homeState.weekdayByWeek[week] || 0) >= 2)
      return { ok: false, reason: `${teamName(home)} already has 2 weekday games in week ${week}` };
    if ((awayState.weekdayByWeek[week] || 0) >= 2)
      return { ok: false, reason: `${teamName(away)} already has 2 weekday games in week ${week}` };
  }
  if (isSaturday) {
    if ((homeState.saturdayByWeek[week] || 0) >= 1)
      return { ok: false, reason: `${teamName(home)} already has a Saturday game in week ${week}` };
    if ((awayState.saturdayByWeek[week] || 0) >= 1)
      return { ok: false, reason: `${teamName(away)} already has a Saturday game in week ${week}` };
  }

  const homeWeekTotal = (homeState.weekdayByWeek[week] || 0) + (homeState.saturdayByWeek[week] || 0);
  const awayWeekTotal = (awayState.weekdayByWeek[week] || 0) + (awayState.saturdayByWeek[week] || 0);
  if (homeWeekTotal >= 3)
    return { ok: false, reason: `${teamName(home)} already has 3 games in week ${week}` };
  if (awayWeekTotal >= 3)
    return { ok: false, reason: `${teamName(away)} already has 3 games in week ${week}` };

  return { ok: true };
}

// ── Slot finder ───────────────────────────────────────────────────────────────
function findSlot(home, away, slots, teamState, fieldUsage, fields, globalBlackouts, season, divisionId) {
  const homeAvail = parseAvailability(home);
  const awayAvail = parseAvailability(away);

  for (const slot of slots) {
    const check = isValidAssignment(home, away, slot, teamState, fieldUsage, globalBlackouts, fields, season, divisionId);
    if (!check.ok) continue;

    const isSat = slot.dayType === 'saturday';
    const field = resolveField(home, fields);
    if (!field) continue;

    const fieldKey = `${field.resolved_id}_${slot.date}`;
    if (fieldUsage[fieldKey]) continue;

    // Determine game time
    let time;
    if (isSat) {
      time = saturdayTime(divisionId, season);
    } else {
      const day = slot.day;
      // Home team's per-day time takes precedence; fall back to away or season default
      time = homeAvail.weekday[day].time || awayAvail.weekday[day].time || season.weekday_time || '18:00';
    }

    return {
      game_id: null,
      division_id: divisionId,
      date: slot.date,
      day: slot.day,
      time,
      home_team_id: home.id,
      home_team_name: teamName(home),
      away_team_id: away.id,
      away_team_name: teamName(away),
      field_id: field.resolved_id,
      field_name: field.name,
      field_address: field.address || '',
      week: slot.week,
      is_rematch: false, // set by caller
      _fieldKey: fieldKey,
    };
  }
  return null;
}

function recordGame(game, teamState, fieldUsage) {
  const homeState = teamState[game.home_team_id];
  const awayState = teamState[game.away_team_id];
  const isSaturday = game.day === 'Saturday';

  homeState.homeCount++;
  homeState.gamesPlayed++;
  homeState.opponents.push(game.away_team_id);

  awayState.awayCount++;
  awayState.gamesPlayed++;
  awayState.opponents.push(game.home_team_id);

  if (isSaturday) {
    homeState.saturdayByWeek[game.week] = (homeState.saturdayByWeek[game.week] || 0) + 1;
    awayState.saturdayByWeek[game.week] = (awayState.saturdayByWeek[game.week] || 0) + 1;
  } else {
    homeState.weekdayByWeek[game.week] = (homeState.weekdayByWeek[game.week] || 0) + 1;
    awayState.weekdayByWeek[game.week] = (awayState.weekdayByWeek[game.week] || 0) + 1;
    homeState.weekdayCounts[game.day] = (homeState.weekdayCounts[game.day] || 0) + 1;
    awayState.weekdayCounts[game.day] = (awayState.weekdayCounts[game.day] || 0) + 1;
  }

  homeState.playedDates.add(game.date);
  awayState.playedDates.add(game.date);

  fieldUsage[game._fieldKey] = true;
}

// ── Slot ordering ─────────────────────────────────────────────────────────────
// Hard availability filtering happens in isValidAssignment; this only orders
// the remaining candidate slots (week spread, avoiding a 3rd game in a week,
// day variety).
function buildSlotList(allSlots, teamA, teamB, teamState) {
  const stA = teamState?.[teamA.id];
  const stB = teamState?.[teamB.id];

  const slots = allSlots.map(s => {
    let score = 0;

    // Spread across weeks; Saturday strongly preferred — all Saturdays score before any weekday
    score += s.week + (s.dayType === 'weekday' ? 8 : 0) + Math.random() * 0.49;

    // 3rd-game-in-week penalty: exhaust all Sat+WD pairs before tripling up
    if (stA && stB) {
      const weekA = (stA.weekdayByWeek[s.week] || 0) + (stA.saturdayByWeek[s.week] || 0);
      const weekB = (stB.weekdayByWeek[s.week] || 0) + (stB.saturdayByWeek[s.week] || 0);
      if (Math.max(weekA, weekB) >= 2) score += 10;
    }

    // Day-variety penalty: discourage repeating the same weekday
    if (s.dayType === 'weekday') {
      const dayA = stA?.weekdayCounts?.[s.day] || 0;
      const dayB = stB?.weekdayCounts?.[s.day] || 0;
      score += (dayA + dayB) * 3;
    }

    return { ...s, _score: score };
  });

  slots.sort((a, b) => a._score - b._score);
  return slots;
}

// ── Division scheduling (one attempt) ────────────────────────────────────────
//
// FIX: Rematch home/away flip — when two teams meet a second time, home and
// away roles are swapped from their first encounter.
//
// Orientation selection accounts for teams that are host-only every weekday
// (isWeekdayHostOnly) when picking who plays home.
//
function tryScheduleDivision(matchups, teams, division, season, fields, globalBlackouts, allSlots, fieldUsage) {
  const teamState = initTeamState(teams);
  const games = [];
  const halfTarget = Math.ceil((season.target_games || 8) / 2);
  const pairKey = (a, b) => teamPairKey(a.id, b.id);

  // Track first-game home/away so rematches can flip correctly
  const firstGameOrient = {}; // pairKey → { homeId, awayId }

  for (const matchup of matchups) {
    const { teamA, teamB } = matchup;
    const availA = parseAvailability(teamA);
    const availB = parseAvailability(teamB);

    // Detect rematch at runtime so flip works regardless of shuffle order.
    const key = pairKey(teamA, teamB);
    const isActualRematch = !!firstGameOrient[key];

    let orientations;

    if (isActualRematch) {
      // Flip home/away from first encounter
      const first = firstGameOrient[key];
      const origHome = teams.find(t => t.id === first.homeId);
      const origAway = teams.find(t => t.id === first.awayId);
      if (origHome && origAway) {
        orientations = [
          { home: origAway, away: origHome }, // flipped (preferred)
          { home: origHome, away: origAway }, // original (fallback if flipped is impossible)
        ];
      }
    }

    if (!orientations) {
      // For weekday-host-only teams, isValidAssignment already enforces home-only on weekdays.
      // Projecting those forced-home weekday games into the effective home count prevents
      // the Saturday orientation from also defaulting to home, which causes imbalance.
      function projectedHomeCount(team, availability) {
        const st = teamState[team.id];
        if (!isWeekdayHostOnly(availability)) return st.homeCount;
        const gamesLeft = (halfTarget * 2) - st.gamesPlayed;
        // Conservative: half of remaining games may be weekday (all forced home)
        return st.homeCount + Math.floor(gamesLeft / 2);
      }

      const aAtCap   = projectedHomeCount(teamA, availA) >= halfTarget;
      const bAtCap   = projectedHomeCount(teamB, availB) >= halfTarget;
      const aHomeAdv = teamState[teamA.id].homeCount - teamState[teamA.id].awayCount;
      const bHomeAdv = teamState[teamB.id].homeCount - teamState[teamB.id].awayCount;

      // isWeekdayHostOnly is only a tiebreaker; balance-based signals take priority
      // so Saturday orientation is driven by actual counts, not the hard weekday rule.
      const aWantsHome = isWeekdayHostOnly(availA);
      const bWantsHome = isWeekdayHostOnly(availB);

      if (aAtCap && !bAtCap) {
        orientations = [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      } else if (bAtCap && !aAtCap) {
        orientations = [{ home: teamA, away: teamB }, { home: teamB, away: teamA }];
      } else if (aHomeAdv < bHomeAdv) {
        orientations = [{ home: teamA, away: teamB }, { home: teamB, away: teamA }];
      } else if (aHomeAdv > bHomeAdv) {
        orientations = [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      } else if (aWantsHome && !bWantsHome) {
        orientations = [{ home: teamA, away: teamB }, { home: teamB, away: teamA }];
      } else if (bWantsHome && !aWantsHome) {
        orientations = [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      } else if (teamState[teamA.id].travelDistance !== teamState[teamB.id].travelDistance) {
        // Travel-balance tiebreaker: give home to whichever team has already
        // traveled more, sending the less-traveled team away this time.
        orientations = teamState[teamA.id].travelDistance > teamState[teamB.id].travelDistance
          ? [{ home: teamA, away: teamB }, { home: teamB, away: teamA }]
          : [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      } else {
        orientations = Math.random() < 0.5
          ? [{ home: teamA, away: teamB }, { home: teamB, away: teamA }]
          : [{ home: teamB, away: teamA }, { home: teamA, away: teamB }];
      }
    }

    let assigned = false;

    for (const { home, away } of orientations) {
      const slots = buildSlotList(allSlots, home, away, teamState);
      const game = findSlot(home, away, slots, teamState, fieldUsage, fields, globalBlackouts, season, division.id);

      if (game) {
        game.is_rematch = isActualRematch;

        // Record first-game orientation for rematch flip
        if (!isActualRematch) {
          firstGameOrient[key] = { homeId: home.id, awayId: away.id };
        }

        recordGame(game, teamState, fieldUsage);

        // Accumulate the away team's travel distance for this game (no-op if either
        // field lacks coordinates), used as an orientation-selection tiebreaker above.
        const dist = distanceMiles(
          parseCoordinates(resolveField(home, fields)?.coordinates),
          parseCoordinates(resolveField(away, fields)?.coordinates)
        );
        if (dist !== null) teamState[away.id].travelDistance += dist;

        games.push(game);
        assigned = true;
        break;
      }
    }

    if (!assigned) {
      return {
        success: false,
        failure: {
          division_id: division.id,
          division_name: divName(division),
          blocking_matchup: `${teamName(teamA)} vs ${teamName(teamB)}`,
          reason: `No valid slot could be found for ${teamName(teamA)} vs ${teamName(teamB)} in ${divName(division)}. ` +
            `Both teams may have conflicting blackouts, full weeks, or field conflicts.`,
        },
      };
    }
  }

  return { success: true, games };
}

// Schedule one division with multiple shuffle attempts.
function scheduleDivision(division, teams, season, fields, globalBlackouts, sharedFieldUsage) {
  const targetGames = division.target_games || season.target_games || 8;

  const noMatchupRules = [...(division.no_matchups || [])];
  for (const team of teams) {
    for (const restriction of (team.restrictions || [])) {
      if (restriction.type === 'no_matchup' && restriction.opponent_program_id) {
        const opponentIds = teams
          .filter(t => t.program_id === restriction.opponent_program_id)
          .map(t => t.id);
        if (opponentIds.length) {
          noMatchupRules.push({ team_ids: [team.id], vs_team_ids: opponentIds });
        }
      }
    }
  }

  const matchupList = buildMatchupList(teams, targetGames, noMatchupRules);
  const allSlots = buildAllSlots(globalBlackouts);

  if (matchupList.length === 0) {
    return {
      success: false,
      failure: {
        division_id: division.id,
        division_name: divName(division),
        reason: 'No valid matchups could be generated (check no_matchup rules and team count)',
      },
    };
  }

  const MAX_ATTEMPTS = 100;
  let lastFailure = null;
  const fieldUsageSnapshot = { ...sharedFieldUsage };

  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    Object.keys(sharedFieldUsage).forEach(k => delete sharedFieldUsage[k]);
    Object.assign(sharedFieldUsage, fieldUsageSnapshot);

    const shuffled = shuffle([...matchupList]);
    const result = tryScheduleDivision(
      shuffled, teams, division, season, fields, globalBlackouts, allSlots, sharedFieldUsage
    );

    if (result.success) {
      return { success: true, games: result.games, division_id: division.id };
    }

    lastFailure = result.failure;
  }

  Object.keys(sharedFieldUsage).forEach(k => delete sharedFieldUsage[k]);
  Object.assign(sharedFieldUsage, fieldUsageSnapshot);

  return { success: false, failure: lastFailure };
}

// ── Top-level ─────────────────────────────────────────────────────────────────
//
// Pre-run validation flags confirmed teams/fields that haven't configured
// availability yet (they default to fully open, so this is informational,
// not blocking) — surfaced in the result as `warnings` for the UI.
//
function scheduleAll(seasonData) {
  const season = seasonData.season;
  const fields = seasonData.fields || [];
  const globalBlackouts = new Set(season.blackout_dates || []);
  for (const weekend of (season.blackout_weekends || [])) {
    if (Array.isArray(weekend.dates)) weekend.dates.forEach(d => globalBlackouts.add(d));
    if (weekend.saturday) globalBlackouts.add(weekend.saturday);
    if (weekend.sunday)   globalBlackouts.add(weekend.sunday);
  }

  const warnings = [];
  for (const team of (seasonData.teams || [])) {
    if (team.confirmed === false) continue;
    if (!team.availability) {
      warnings.push({
        type: 'availability_warning',
        team_id: team.id,
        team_name: teamName(team),
        message: `${teamName(team)} has not set availability — defaulting to fully available`,
      });
    }
  }
  for (const field of fields) {
    if (!field.availability) {
      warnings.push({
        type: 'availability_warning',
        field_id: field.id,
        message: `${field.name} has not set availability — defaulting to fully open`,
      });
    }
  }

  const allGames = [];
  const failures = [];
  let gameIdCounter = 1;

  const startYear = (season.start || season.start_date || '').slice(2, 4)
    || String(new Date().getFullYear()).slice(2);
  const seasonName = (season.name || '').toLowerCase();
  const seasonNum = seasonName.includes('fall') ? '2' : '1';
  const gameIdPrefix = startYear + seasonNum;

  const sharedFieldUsage = {};

  for (const division of seasonData.divisions) {
    const divTeams = (seasonData.teams || []).filter(t =>
      t.division_id === division.id && t.confirmed !== false
    );

    if (divTeams.length < 2) {
      failures.push({
        division_id: division.id,
        division_name: divName(division),
        reason: `Only ${divTeams.length} confirmed team(s) — need at least 2`,
      });
      continue;
    }

    const result = scheduleDivision(division, divTeams, season, fields, globalBlackouts, sharedFieldUsage);

    if (result.success) {
      for (const game of result.games) {
        game.game_id = parseInt(gameIdPrefix + String(gameIdCounter++).padStart(3, '0'), 10);
      }
      allGames.push(...result.games);
    } else {
      failures.push(result.failure);
    }
  }

  return {
    success: failures.length === 0,
    games: allGames,
    failures,
    warnings,  // NEW: soft warnings surfaced to the UI
    generated_at: new Date().toISOString(),
    total_games: allGames.length,
  };
}

// ── Game edit validation ──────────────────────────────────────────────────────

function validateGameEdit(editedGame, allGames, season) {
  const violations = [];
  const { id, date, time, field_id, home_team_id, away_team_id } = editedGame;

  if (home_team_id === away_team_id) {
    violations.push('Home team and away team cannot be the same.');
  }

  const globalBlackouts = new Set(season.blackout_dates || []);
  if (season.blackout_weekends) {
    for (const weekend of season.blackout_weekends) {
      if (weekend.saturday) globalBlackouts.add(weekend.saturday);
      if (weekend.sunday)   globalBlackouts.add(weekend.sunday);
      if (weekend.dates)    for (const d of weekend.dates) globalBlackouts.add(d);
    }
  }

  let weekEntry = null;
  let dateType = null;
  for (const wk of SEASON_WEEKS) {
    if (wk.weekdays.includes(date)) { weekEntry = wk; dateType = 'weekday'; break; }
    if (wk.saturday === date)        { weekEntry = wk; dateType = 'saturday'; break; }
  }

  if (!weekEntry) {
    violations.push(`${date} is not a valid season date.`);
    return violations;
  }

  if (globalBlackouts.has(date)) {
    violations.push(`${date} is a global blackout date.`);
  }

  const teams = season._teams || [];
  const homeTeam = teams.find(t => t.id === home_team_id);
  const awayTeam = teams.find(t => t.id === away_team_id);

  if (homeTeam && (homeTeam.blackout_dates || []).includes(date))
    violations.push(`Home team (${teamName(homeTeam)}) is blacked out on ${date}.`);
  if (awayTeam && (awayTeam.blackout_dates || []).includes(date))
    violations.push(`Away team (${teamName(awayTeam)}) is blacked out on ${date}.`);

  const others = allGames.filter(g => g.game_id !== id && g.id !== id);

  const fieldConflict = others.find(g => g.field_id === field_id && g.date === date && g.time === time);
  if (fieldConflict)
    violations.push(`Field is already booked at ${date} ${time} (game #${fieldConflict.game_id || fieldConflict.id}).`);

  const homeConflict = others.find(g =>
    (g.home_team_id === home_team_id || g.away_team_id === home_team_id) && g.date === date && g.time === time
  );
  if (homeConflict)
    violations.push(`Home team already has a game at ${date} ${time}.`);

  const awayConflict = others.find(g =>
    (g.home_team_id === away_team_id || g.away_team_id === away_team_id) && g.date === date && g.time === time
  );
  if (awayConflict)
    violations.push(`Away team already has a game at ${date} ${time}.`);

  const week = weekEntry.week;
  const isSaturday = dateType === 'saturday';
  const day = dayName(date);

  // ── Consecutive-day check ──────────────────────────────────────────────────
  const prevDay = adjacentDate(date, -1);
  const nextDay = adjacentDate(date, +1);
  const homeConsec = others.find(g =>
    (g.home_team_id === home_team_id || g.away_team_id === home_team_id) &&
    (g.date === prevDay || g.date === nextDay)
  );
  if (homeConsec)
    violations.push(`Home team would play on consecutive days (existing game on ${homeConsec.date}).`);
  const awayConsec = others.find(g =>
    (g.home_team_id === away_team_id || g.away_team_id === away_team_id) &&
    (g.date === prevDay || g.date === nextDay)
  );
  if (awayConsec)
    violations.push(`Away team would play on consecutive days (existing game on ${awayConsec.date}).`);

  // ── Team availability checks (soft — informational, "Save Anyway" overrides) ──
  const availKey = isSaturday ? saturdayBlock(time) : day;
  const availLabel = isSaturday ? `the ${availKey} Saturday block` : day;
  if (homeTeam) {
    const status = parseAvailability(homeTeam)[isSaturday ? 'saturday' : 'weekday'][availKey];
    const homeStatus = isSaturday ? status : status.status;
    if (homeStatus === 'none')
      violations.push(`Home team (${teamName(homeTeam)}) is not available for ${availLabel}.`);
    else if (homeStatus === 'travel')
      violations.push(`Home team (${teamName(homeTeam)}) is only available to travel for ${availLabel}, not host.`);
  }
  if (awayTeam) {
    const status = parseAvailability(awayTeam)[isSaturday ? 'saturday' : 'weekday'][availKey];
    const awayStatus = isSaturday ? status : status.status;
    if (awayStatus === 'none')
      violations.push(`Away team (${teamName(awayTeam)}) is not available for ${availLabel}.`);
    else if (awayStatus === 'host')
      violations.push(`Away team (${teamName(awayTeam)}) is only available to host for ${availLabel}, not travel.`);
  }

  if (isSaturday) {
    const homeSat = others.filter(g =>
      (g.home_team_id === home_team_id || g.away_team_id === home_team_id) &&
      g.week === week && g.day === 'Saturday'
    ).length;
    if (homeSat >= 1) violations.push(`Home team already has a Saturday game in week ${week}.`);

    const awaySat = others.filter(g =>
      (g.home_team_id === away_team_id || g.away_team_id === away_team_id) &&
      g.week === week && g.day === 'Saturday'
    ).length;
    if (awaySat >= 1) violations.push(`Away team already has a Saturday game in week ${week}.`);
  } else {
    const homeWd = others.filter(g =>
      (g.home_team_id === home_team_id || g.away_team_id === home_team_id) &&
      g.week === week && g.day !== 'Saturday'
    ).length;
    if (homeWd >= 2) violations.push(`Home team already has 2 weekday games in week ${week}.`);

    const awayWd = others.filter(g =>
      (g.home_team_id === away_team_id || g.away_team_id === away_team_id) &&
      g.week === week && g.day !== 'Saturday'
    ).length;
    if (awayWd >= 2) violations.push(`Away team already has 2 weekday games in week ${week}.`);

    const homeTot = others.filter(g =>
      (g.home_team_id === home_team_id || g.away_team_id === home_team_id) && g.week === week
    ).length;
    if (homeTot >= 3) violations.push(`Home team already has 3 games in week ${week}.`);

    const awayTot = others.filter(g =>
      (g.home_team_id === away_team_id || g.away_team_id === away_team_id) && g.week === week
    ).length;
    if (awayTot >= 3) violations.push(`Away team already has 3 games in week ${week}.`);
  }

  return violations;
}

module.exports = { scheduleAll, validateGameEdit, SEASON_WEEKS, dayName, teamName };
